### ISSUE TITLE
/user/publicmodlogs account on Reddit suspended?

### ISSUE THREAD

**Issue by davidshares** [snew/snew#10]
Hello,

It's come to my attention that the /user/publicmodlogs account on Reddit has been suspended, which can be seen here: https://www.reddit.com/user/publicmodlogs/about.json 

`{"kind": "t2", "data": {"is_suspended": true, "name": "publicmodlogs"}}`

Is this correct? The public mod logs seems to be broken, and this is probably related. If so, can you try to talk to Reddit admins to get it reinstated (don't know why it was suspended), or alternatively is there another account that you use to implement the public mod logs separately? By the way, some Redditor's have already opened an issue in the /r/ModSupport subreddit: https://reddit.com/r/ModSupport/comments/8k3f0v/is_publicmodlogs_suspended_and_what_can_be_done/ 

Thanks.

**Comment by davidshares** [comment]
Update comment from Reddit admins for you:

> The person who runs the bot just needs to check it's inbox for the message we sent them with some instructions - the bot is not permanently suspended. At times accounts can be locked until the password is changed and that is the case here. When the account was locked we sent the account owner an email and a PM letting them know the account will be unlocked as soon as they update their password. https://reddit.com/r/ModSupport/comments/8k3f0v/is_publicmodlogs_suspended_and_what_can_be_done/dz4rdrg/

**Comment by go1dfish** [comment]
Thanks, I'll probably need to update the feed hash for publicmodlogs if/when it gets restored.  The account is managed by mumberthrax on reddit.

For now I've linked to the situation on snew's modlog page, example:

https://snew.github.io/r/cryptocurrency/about/log

**Comment by go1dfish** [comment]
This has been resolved:

https://github.com/snew/snew/pull/11

Thanks for helping
