### ISSUE TITLE
Not saving information - Does Not Work

### ISSUE THREAD

**Issue by SoftNotWork** [snew/snew#12]
We tried to save a spam user's post history, linked it to moderators, they deleted the posts, and snew saved nothing. 

/user/whatever/overview does not save anything. They were able to spam, harass, and threaten. We have no proof. 

Why doesn't it save information from reddit? We loaded the comments in every mirror possible one after another as they were live on the site. We used every single mirror we could find before they deleted the posts.

**Comment by go1dfish** [comment]
snew is a reddit client, it doesn't store anything.

You should look into pushshift.io https://reddit.com/r/pushshift

That is the data service powering the removal restoration snew does, and it likely has the data you are looking for.
