### ISSUE TITLE
Quarantined subreddits are not available 

### ISSUE THREAD

**Issue by Ojisan1** [snew/snew#22]
Quarantined subreddits display a warning page before the post itself is shown, and it seems that snew is not set up to handle the extra step. 

More on quarantine here: https://www.reddit.com/r/announcements/comments/9jf8nh/revamping_the_quarantine_function/

**Comment by go1dfish** [comment]
It's not possible to access quarantined subreddit data from the reddit API without being logged in so it's not possible for snew to operate normally in quarantined subs.

If pushshift itself is able to detect removals in quarantined communities I may be able to leverage that somehow but it wont be trivial; would be similar to what I'd eventually like to do to restore banned subs in snew.
