### ISSUE TITLE
ceddit.com ssl certificate expired 5 months ago

### ISSUE THREAD

**Issue by edwardslabs** [snew/snew#4]
Wasn't sure of another way to contact you, but it looks like your let's encrypt automatic renewals aren't working. I dig the ceddit.com site and hope you update the certificate soon. Thanks!

**Comment by go1dfish** [comment]
This has been fixed, was hoping webfaction would support automatic lets encryption renewal but they still don't

So I'll try to keep on top of it manually.

Also I rebuilt the app from the ground up.

**Comment by edwardslabs** [comment]
Thanks have a great day!

**Comment by alexwh** [comment]
This has happened again, btw.
Have you looked into this?
https://github.com/will-in-wi/letsencrypt-webfaction
