### ISSUE TITLE
Please make the open mod logs searchable, and individual actions easy to link to

### ISSUE THREAD

**Issue by TiagoTiago** [snew/snew#5]
Having to go thru pages one by one to try to find something from months ago sucks.

**Comment by go1dfish** [comment]
You may want to look into https://modlogs.fyi if you are a moderator.  It actually archives mod logs and provides additional searching capabilities.

AFAIK reddit's modlogs are not searchable, and snew pulls public modlogs directly from reddit. (through an ajax proxy)

If reddit does support searching mod logs it should be supported in the public mod logs, any query params to /r/subreddit/about/log like ?mod should be supported already.
